name: Update Google Spreadsheet

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DEBUG: "0"
      SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SA_JSON }} # JSON raw
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      UPDATE_INTERVAL_DAYS: 8

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -e .

      - name: Run update
        run: update-spreadsheet
